### PR TITLE
Spark is now Particle

### PR DESCRIPTION
**Pull request by kristinpeterson**
https://www.particle.io/

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@netarc can you please review?

Spark is now [Particle](https://www.particle.io/)

**Comment by netarc** [comment]
:+1:

**Comment by fsaravia** [comment]
@kristinpeterson, @stream7: Should we bump the version number and do a release?

**Comment by stream7** [comment]
@fsaravia I'm not sure. Let's wait for @kristinpeterson. When we publish a release do we need to push it to some kind of registry or just github?

**Comment by kristinpeterson** [comment]
@fsaravia great catch! can you please bump the version number?

@stream7 just github

**Comment by fsaravia** [comment]
Done!

**Pull request merged**
